### ISSUE TITLE
Transfer `polkadot_network_directory` over to polkadot-cloud

### ISSUE THREAD

**Issue by wirednkod** [polkadot-cloud/library#187]
Following [this comment](https://github.com/paritytech/polkadot_network_directory) by @PierreBesson this issue is opened for tracking the progress for this transfer.

There has been already [an attempt](https://github.com/polkadot-cloud/library/pull/5) which though is more of a transfer of the data and conversion (to JSON) from the aforementioned repo.

This is tracking the actual move and usage of the assets from polkadot_network_directory to polkadot-cloud

**Comment by PierreBesson** [comment]
As maintainer of [paritytech/polkadot_network_directory](https://github.com/paritytech/polkadot_network_directory), I confirm that we want to transfer our network list to polkadot-cloud so that this project become a reputable and easy to consume source to get info about existing blockchain networks (RPC, bootnodes, etc.).

I suggest we keep the files in the YAML format we defined with @chevdor using [our JSON schema validator file](https://github.com/paritytech/polkadot_network_directory/blob/c3c446d8ac974bae4dc95074dfcc797e875623a1/schemas/pnd_chain-schema.json) to check user contributions. This is easier for third-party to contribute to than pure JS code (eg. what is done for validators [packages/assets/lib/validators/index.tsx](https://github.com/polkadot-cloud/library/blob/main/packages/assets/lib/validators/index.tsx)). I would also recommend that you also adopt our approach for the existing validator list (so we will have 1 yaml file per validator). IMO this is a big downside of polkadot.js that contributors have to add new RPC endpoints within the code base and not as config files.

I would import polkadot_network_directory into polkadot-cloud like this:
- `/packages/assets/info/chains/`: contain all yaml files currently present in [polkadot_network_directory//chain_info](https://github.com/paritytech/polkadot_network_directory/tree/master/chain_info)
- use gulp or another script to import data from yaml files and aggregate them
- set up a github action to validate that yaml files submitted in PRs are correct according to the JSON schema. See our [`check_all.sh`](https://github.com/paritytech/polkadot_network_directory/blob/master/scripts/check_all.sh) script (this could also be a JS implementation of this) check.
- publish a big [`chains.json`](https://paritytech.github.io/polkadot_network_directory/chains.json) under polkadot.cloud and deprecate polkadot_network_directory.

**Comment by wirednkod** [comment]
After some discussions with @chevdor, @PierreBesson and @rossbulat it was agreed that both:
- https://github.com/paritytech/polkadot_network_directory
- https://github.com/chevdor/subrpc/

can move under @polkadot-cloud organisation. Was also agreed that we shall keep it as generic as possible, and with automations (gulp etc) we can release for different languages respective packages and Will can help us maintain these 2 repos.

**Comment by chevdor** [comment]
The correct list is:
`subrpc` will probably be involved but stay where it is for now.

- https://github.com/paritytech/polkadot_network_directory
- ~~https://github.com/chevdor/subrpc/~~
- https://github.com/paritytech/substrate-assets

**Comment by wirednkod** [comment]
Thank you for the correction! I altered it

**Comment by chevdor** [comment]
See:
- https://github.com/polkadot-cloud/polkadot_network_directory
- https://github.com/polkadot-cloud/substrate-assets

**Comment by chevdor** [comment]
I cannot close this issue but I think it can be closed now.

**Comment by wirednkod** [comment]
Since the https://github.com/polkadot-cloud/polkadot_network_directory and https://github.com/polkadot-cloud/substrate-assets are now transferred this can close. Thank you so much @chevdor 🙏🏽
